# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dashboard::Application.load_tasks

namespace :dashboard do
  task :setup_db do
    puts 'Running setup_or_migrate'
    Rake::Task['db:setup_or_migrate'].execute
    puts 'Running seed:all'
    Rake::Task['seed:all'].execute
    puts 'Ran seed:all'
  end
end
